### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by jlnjnsn** [uva/app-studio#1]
r.1) Your challenge for this project is to implement the game of Ghost as a native iOS app.
->
Your challenge for this project is to implement the game of Ghost as a native app.

r.4) Our goal in this problem is to implement an interactive Python program that allows...
->
Our goal in this problem is to implement an interactive program that allows...

**Comment by stgm** [comment]
Fixed in 27316c8b85c6efc363c5beca0c429a4cb7916793
